---
title: "WebRTC Cellular 03/03 Experiment: One-way Delay"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  ue_data_file: "ue-rtp.csv"
  enb_data_file: "enb-rtp.csv"
  fig_path: "fig/"
---

```{R setup, include=FALSE}
source("../r/setup.R")

knitr::opts_chunk$set(dev=c("png", "pdf"), fig.width=9, fig.height=4.5,
  fig.align="center", fig.keep="high", fig.path=params$fig_path) 
```

```{r import}
pkts_ue <- read_csv(params$ue_data_file, col_types="") %>%
  mutate(encap = as.factor(encap), rtp_ssrc = as.factor(rtp_ssrc), rtp_pt = as.factor(rtp_pt))

pkts_enb <- read_csv(params$enb_data_file, col_types="") %>%
  mutate(encap = as.factor(encap), rtp_ssrc = as.factor(rtp_ssrc), rtp_pt = as.factor(rtp_pt))
```

```{r}
base_ts_s <- max(
  min(pkts_ue$ts_s),
  min(pkts_enb$ts_s))

pkts_ue %<>%
  filter(ts_s >= base_ts_s) %>%
  mutate(ts_s = ts_s - base_ts_s, ts_ms_rel = ts_s * 1e3 + ts_us / 1e3) %>%
  relocate(ts_ms_rel, .after = ts_us)

pkts_enb %<>%
  filter(ts_s >= base_ts_s) %>%
  mutate(ts_s = ts_s - base_ts_s, ts_ms_rel = ts_s * 1e3 + ts_us / 1e3) %>%
  relocate(ts_ms_rel, .after = ts_us)
```
# 
# Video: VP8 at 90 kHz with Simulcast + RTX
# * main PT = 96
# * RTX PT = 97
# 
# Audio: Opus at 48 kHz with in-band FEC
# * main PT = 111
# 

```{r}
pkts_ue %>%
  group_by(ip_src, ip_dst, udp_src, udp_dst, rtp_ssrc, rtp_pt) %>%
  summarize(n = n(), mean_media_len = mean(media_len), total_frame_len_mb = sum(frame_len) / 1000 / 1000,
            .groups = "drop")
```
```{r}
pkts_enb %>%
  group_by(ip_src, ip_dst, udp_src, udp_dst, rtp_ssrc, rtp_pt) %>%
  summarize(n = n(), min_ts_ms_rel = min(ts_ms_rel), max_ts_ms_rel = max(ts_ms_rel),
            .groups = "drop")
```

```{r}
one_way <- left_join(
  pkts_ue %>%
    select(ts_ms_rel, rtp_ssrc, rtp_pt, rtp_seq, rtp_ts, rtp_tw_seq4),
  pkts_enb %>%
    select(ts_ms_rel, rtp_ssrc, rtp_pt, rtp_seq, rtp_ts, rtp_tw_seq4),
  join_by("rtp_ts", "rtp_seq", "rtp_tw_seq4", "rtp_ssrc", "rtp_pt"), suffix = c("_ue", "_enb")) %>%
  filter(!is.na(ts_ms_rel_enb)) %>%
  mutate(owd_ms = ts_ms_rel_enb - ts_ms_rel_ue)
```
 
```{r owd-up-cdf, fig.width = 6, fig.height = 4}
one_way %>%
  select(owd_ms) %>%
  ggplot(aes(x = owd_ms)) +
    stat_ecdf(color = "dodgerblue4") +
    labs(title = "RTP Uplink One-Way Delay (UE → eNB)", x = "One-Way Delay [ms]", y = "CDF") +
    theme_om()
```
```{r inter-pkt-cdf, fig.width = 6, fig.height = 4}
one_way %>%
  select(ts_ms_rel_ue, ts_ms_rel_enb) %>%
  mutate(ts_ms_rel_delta_ue = ts_ms_rel_ue  - lag(ts_ms_rel_ue)) %>%
  mutate(ts_ms_rel_delta_enb = ts_ms_rel_enb - lag(ts_ms_rel_enb)) %>%
  pivot_longer(c("ts_ms_rel_delta_ue", "ts_ms_rel_delta_enb"), names_to = "type", 
               values_to="ts_ms_rel_delta") %>%
  filter(!is.na(ts_ms_rel_delta)) %>%
  ggplot(aes(x = ts_ms_rel_delta, color = type)) +
    stat_ecdf() +
    labs(title = "RTP Inter-Packet Time (UE → eNB)", x = "Time between Packets [ms]", y = "CDF", 
         color = "location") +
    theme_om()
```
# 
# 

```{r}
one_way %>%
  mutate(ts_s_rel_ue = ts_ms_rel_ue / 1000) %>%
  ggplot(aes(x = ts_s_rel_ue, y = rtp_tw_seq4)) +
    geom_line()
```
# 
```{r, fig.width = 15, fig.height=100}
one_way %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  ggplot(aes(x = rtp_tw_seq4_mod1000, y = owd_ms)) +
    labs(x = "RTP seq. % 1000", y = "UE-eNB one-way delay [ms]") +
    ylim(0,NA) +
    scale_x_continuous(breaks = seq(0, 1000, 100), expand = c(0.0125, 0)) +
    geom_line(color = "dodgerblue4") +
    facet_wrap(~slice, ncol=1) +
    theme_om()
```

```{r owd-5, fig.width = 12, fig.height=3}
one_way %>%
  filter(rtp_tw_seq4 > 26000 & rtp_tw_seq4 <= 26100 & ts_ms_rel_ue < 180000) %>%
  ggplot(aes(x = rtp_tw_seq4, y = owd_ms, color = rtp_ssrc)) +
    labs(x = "RTP seq.", y = "UE-eNB one-way delay [ms]", color = "RTP SSRC") +
    scale_x_continuous(expand = c(0.0125, 0)) +
    geom_line(color = "gray50") +
    geom_point() +
    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.98, 0.9))
```

```{r owd-4, fig.width = 12, fig.height=3}
one_way %>%
  filter(rtp_tw_seq4 > 21100 & rtp_tw_seq4 <= 21150 & ts_ms_rel_ue < 180000) %>%
  ggplot(aes(x = rtp_tw_seq4, y = owd_ms, color = rtp_ssrc)) +
    labs(x = "RTP seq.", y = "UE-eNB one-way delay [ms]", color = "RTP SSRC") +
    scale_x_continuous(expand = c(0.0125, 0)) +
    geom_line(color = "gray50") +
    geom_point() +
    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.445, 0.9))
```

```{r owd-1, fig.width = 12, fig.height=3}
one_way %>%
  filter(rtp_tw_seq4 > 16100 & rtp_tw_seq4 <= 16200 & ts_ms_rel_ue < 180000) %>%
  ggplot(aes(x = rtp_tw_seq4, y = owd_ms, color = rtp_ssrc)) +
    labs(x = "RTP seq.", y = "UE-eNB one-way delay [ms]", color = "RTP SSRC") +
    scale_x_continuous(expand = c(0.0125, 0)) +
    geom_line(color = "gray50") +
    geom_point() +
    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.445, 0.9))
```

```{r owd-2, fig.width = 12, fig.height=3}
one_way %>%
  filter(rtp_tw_seq4 > 1500 & rtp_tw_seq4 <= 1900 & ts_ms_rel_ue > 180000) %>%
  ggplot(aes(x = rtp_tw_seq4, y = owd_ms, color = rtp_ssrc)) +
    labs(x = "RTP seq.", y = "UE-eNB one-way delay [ms]", color = "RTP SSRC") +
    scale_x_continuous(expand = c(0.0125, 0)) +
    geom_line(color = "gray50") +
    geom_point() +
    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.98, 0.9))
```

```{r owd-3, fig.width = 12, fig.height=3}
one_way %>%
  filter(rtp_tw_seq4 > 1600 & rtp_tw_seq4 < 1700 & ts_ms_rel_ue > 180000) %>%
  ggplot(aes(x = rtp_tw_seq4, y = owd_ms, color = rtp_ssrc)) +
    labs(x = "RTP seq.", y = "UE-eNB one-way delay [ms]", color = "RTP SSRC") +
    scale_x_continuous(expand = c(0.0125, 0)) +
    geom_line(color = "gray50") +
    geom_point() +
    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.18, 0.9))
```


```{r bar-1, fig.width = 12, fig.height=5}
one_way %>%
  filter(rtp_tw_seq4 > 1600 & rtp_tw_seq4 < 1700 & ts_ms_rel_ue > 180000) %>%
  ggplot(aes(x = ts_ms_rel_ue, xend = ts_ms_rel_enb, y = rtp_tw_seq4, yend = rtp_tw_seq4, color = rtp_ssrc)) +
    labs(x = "Time [ms]", y = "RTP seq.", color = "RTP SSRC") +
    scale_x_continuous(n.breaks = 20, expand = c(0.0125, 0)) +
    geom_segment(linewidth = 1.25) +
    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.18, 0.935))
```


```{r}
one_way %>%
  filter(rtp_pt == 46)
```


  

```{r bar-2, fig.width = 12, fig.height=5}
one_way %>%
  filter(rtp_tw_seq4 > 26000 & rtp_tw_seq4 <= 26100  & ts_ms_rel_ue > 180000) %>%
  ggplot(aes(x = ts_ms_rel_ue, xend = ts_ms_rel_enb, y = rtp_tw_seq4, yend = rtp_tw_seq4, color = rtp_ssrc)) +
    labs(x = "Time [ms]", y = "RTP seq.", color = "RTP SSRC") +
    scale_x_continuous(n.breaks = 20, expand = c(0.0125, 0)) +
    geom_segment(linewidth = 1.25) +
    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.18, 0.935))
```

# 
# ```{r owd-2, fig.width = 12, fig.height=3}
# one_way %>%
#   filter(ts_ms_rel_ue < 300000) %>%
#   filter(rtp_tw_seq3 > 23300 & rtp_tw_seq3 <= 23360) %>%
#   ggplot(aes(x = rtp_tw_seq3, y = owd_ms, color = rtp_ssrc)) +
#     labs(x = "RTP seq.", y = "UE-eNB one-way delay [ms]", color = "RTP SSRC") +
#     scale_x_continuous(expand = c(0.0125, 0)) +
#     ylim(NA, 50) +
#     geom_line(color = "gray50") +
#     geom_point() +
#     theme_om() +
#     theme(legend.direction = "horizontal", legend.position = c(0.445, 0.9))
# ```
# ```{r bar-2, fig.width = 12, fig.height=5}
# one_way %>%
#   filter(ts_ms_rel_ue < 300000) %>%
#   filter(rtp_tw_seq3 > 23300 & rtp_tw_seq3 <= 23360) %>%
#   ggplot(aes(x = ts_ms_rel_ue, xend = ts_ms_rel_enb, y = rtp_tw_seq3, yend = rtp_tw_seq3, color = rtp_ssrc)) +
#     labs(x = "Time [ms]", y = "RTP seq.", color = "RTP SSRC") +
#     scale_x_continuous(n.breaks = 20, expand = c(0.0125, 0)) +
#     geom_segment(linewidth = 1.25) +
#     theme_om() +
#     theme(legend.direction = "horizontal", legend.position = c(0.45, 0.935))
# ```