---
title: "WebRTC Cellular 03/18 Experiment: Data Preparation"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  ue_data_file: "ue-rtp.csv"
  enb_data_file: "enb-rtp.csv"
  sfu_data_file: "sfu-rtp.csv"
  fig_path: "fig/"
---

```{R setup, include=FALSE}
source("../r/setup.R")

knitr::opts_chunk$set(dev=c("png", "pdf"), fig.width=9, fig.height=4.5,
  fig.align="center", fig.keep="high", fig.path=params$fig_path) 
```

```{r import}
pkts_ue <- read_csv(params$ue_data_file, col_types="") %>%
  mutate(encap = as.factor(encap), rtp_ssrc = as.factor(rtp_ssrc), rtp_pt = as.factor(rtp_pt))

pkts_enb <- read_csv(params$enb_data_file, col_types="") %>%
  mutate(encap = as.factor(encap), rtp_ssrc = as.factor(rtp_ssrc), rtp_pt = as.factor(rtp_pt))

pkts_sfu <- read_csv(params$sfu_data_file, col_types="") %>%
  mutate(encap = as.factor(encap), rtp_ssrc = as.factor(rtp_ssrc), rtp_pt = as.factor(rtp_pt))
```

```{r}

joined <- full_join(
  full_join(
    pkts_ue %>% select(ts_s, ts_us,rtp_ts, rtp_seq, rtp_tw_seq4, rtp_ssrc, rtp_pt, frame_len, media_len),
    pkts_enb %>% select(ts_s, ts_us,rtp_ts, rtp_seq, rtp_tw_seq4),
    by = join_by("rtp_ts", "rtp_seq", "rtp_tw_seq4"),
    suffix = c("_ue", "_enb")
  ),
  pkts_sfu %>% select(ts_s, ts_us,rtp_ts, rtp_seq, rtp_tw_seq4),
  by = join_by("rtp_ts", "rtp_seq", "rtp_tw_seq4")) %>%
  rename(ts_s_sfu = ts_s, ts_us_sfu = ts_us) %>%
  filter(!is.na(ts_s_ue) & !is.na(ts_s_enb), !is.na(ts_s_sfu)) %>%
  arrange(ts_s_ue)

start_s <- min(joined$ts_s_ue)

joined %<>% mutate(
    ts_s_ue = ts_s_ue - start_s,
    ts_s_enb = ts_s_enb - start_s,
    ts_s_sfu = ts_s_sfu - start_s,
    ts_ms_ue = ts_s_ue * 1000 + ts_us_ue / 1000,
    ts_ms_enb = ts_s_enb * 1000 + ts_us_enb / 1000,
    ts_ms_sfu = ts_s_sfu * 1000 + ts_us_sfu / 1000) %>%
  select(-c(ts_s_ue, ts_us_ue, ts_s_enb, ts_us_enb, ts_s_sfu, ts_us_sfu)) %>%
  relocate(ts_ms_ue, ts_ms_enb, ts_ms_sfu)

write_csv(joined, "joined.csv")
```


```{r}
joined %>%
  group_by(rtp_ssrc, rtp_pt) %>%
  summarize(n = n(), .groups = "drop")
```
