---
title: "WebRTC Cellular 11/13 Experiment: One-way Delay"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  core_data_file: "test-111323-4gcore.csv"
  ue_data_file: "test-111323-ue.csv"
  fig_path: "fig/"
---

```{R setup, include=FALSE}
source("../r/setup.R")

knitr::opts_chunk$set(dev=c("png", "pdf"), fig.width=9, fig.height=4.5,
  fig.align="center", fig.keep="high", fig.path=params$fig_path) 
```

```{r import}
pkts_4gcore <- read_csv(params$core_data_file, col_types="")
pkts_ue <- read_csv(params$ue_data_file, col_types="")
```

Video: VP8 at 90 kHz with Simulcast + RTX
* main PT = 96
* RTX PT = 97

Audio: Opus at 48 kHz with in-band FEC
* main PT = 111

```{r}
pkts_4gcore %>%
  group_by(ip_src, ip_dst, gtp_ip_src, gtp_ip_dst, rtp_ssrc, rtp_pt) %>%
  summarize(n = n(), .groups = "drop")
```

```{r}
pkts_ue %>%
  group_by(ip_src, ip_dst, gtp_ip_src, gtp_ip_dst, rtp_ssrc, rtp_pt) %>%
  summarize(n = n(), .groups = "drop")
```

```{r}
pkts_ue %>%
  filter(rtp_ssrc == 665559020 & rtp_seq == 14009)
```

```{r}
pkts_4gcore %>%
  filter(rtp_ssrc == 665559020 & rtp_seq == 14007)
```

```{r}
pkts_ue %>%
  filter(rtp_ssrc == 665559020)
```


```{r}

one_way_delay <- left_join(
  pkts_ue %>%
    filter(ts_s >= 1699903019) %>%
    mutate(ts = (ts_s - 1699903019) * 1e6 + ts_us) %>%
    select(-c(ts_s, ts_us)) %>%
    select(rtp_seq, rtp_ts, rtp_tw_seq, ts),

  pkts_4gcore %>%
    filter(ts_s >= 1699903019) %>%
    mutate(ts = (ts_s - 1699903019) * 1e6 + ts_us) %>%
    select(-c(ts_s, ts_us)) %>%
    filter(encap == "gtp" & ip_ttl == 64) %>%
    select(rtp_seq, rtp_ts, rtp_tw_seq, ts),
  
  by = join_by(rtp_seq, rtp_ts, rtp_tw_seq), suffix = c("_ue", "_4gcore")
) %>%
  mutate(delay = (ts_4gcore - ts_ue) / 1000)  %>%
  mutate(ts = ts_4gcore / 1e6)
```

```{r 0-100, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 0 & ts < 100) %>%
  ggplot(aes(x = ts, y = delay)) +
    ylim(0, 100) +
    scale_x_continuous("Time [s]", seq(0, 100), seq(0, 100), c(0, 100), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```

```{r 100-200, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 100 & ts < 200) %>%
  ggplot(aes(x = ts, y = delay)) +
    ylim(0, 100) +
    scale_x_continuous("Time [s]", seq(100, 200), seq(100, 200), c(100, 200), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```

```{r 200-300, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 200 & ts < 300) %>%
  ggplot(aes(x = ts, y = delay)) +
    ylim(0, 100) +
    scale_x_continuous("Time [s]", seq(200, 300), seq(200, 300), c(200, 300), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```

```{r 300-400, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 300 & ts < 400) %>%
  ggplot(aes(x = ts, y = delay)) +
    ylim(0, 100) +
    scale_x_continuous("Time [s]", seq(300, 400), seq(300, 400), c(300, 400), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```

```{r 400-500, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 400 & ts < 500) %>%
  ggplot(aes(x = ts, y = delay)) +
    ylim(0, 100) +
    scale_x_continuous("Time [s]", seq(400, 500), seq(400, 500), c(400, 500), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```

```{r 0-100-tw-seq, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 0 & ts < 100) %>%
  ggplot(aes(x = rtp_tw_seq, y = delay)) +
    ylim(0, 100) +
    # scale_x_continuous("Time [s]", seq(0, 100), seq(0, 100), c(0, 100), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```

```{r 100-200-tw-seq, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 100 & ts < 200) %>%
  ggplot(aes(x = rtp_tw_seq, y = delay)) +
    ylim(0, 100) +
    # scale_x_continuous("Time [s]", seq(0, 100), seq(0, 100), c(0, 100), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```

```{r 200-300-tw-seq, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 200 & ts < 300) %>%
  ggplot(aes(x = rtp_tw_seq, y = delay)) +
    ylim(0, 100) +
    # scale_x_continuous("Time [s]", seq(0, 100), seq(0, 100), c(0, 100), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```

```{r 300-400-tw-seq, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 300 & ts < 400) %>%
  ggplot(aes(x = rtp_tw_seq, y = delay)) +
    ylim(0, 100) +
    # scale_x_continuous("Time [s]", seq(0, 100), seq(0, 100), c(0, 100), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```

```{r 400-500-tw-seq, fig.width = 800, fig.height = 10}
one_way_delay %>%
  filter(ts >= 400 & ts < 500) %>%
  ggplot(aes(x = rtp_tw_seq, y = delay)) +
    ylim(0, 100) +
    # scale_x_continuous("Time [s]", seq(0, 100), seq(0, 100), c(0, 100), expand = c(0, 0)) +
    scale_y_continuous("One-way Delay [ms]", seq(0, 100, 10), seq(0, 100, 10), c(0, 100)) +
    geom_line(color = "dodgerblue4") + geom_point(color = "dodgerblue4") +
    theme_bw()
```