---
title: "WebRTC Cellular 11/13 Experiment: Data Rates from UE"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  ue_data_file: "test-111323-ue.csv"
  fig_path: "fig/"
---

```{R setup, include=FALSE}
source("../r/setup.R")

knitr::opts_chunk$set(dev=c("png", "pdf"), fig.width=9, fig.height=4.5,
  fig.align="center", fig.keep="high", fig.path=params$fig_path) 
```

```{r import}
pkts_ue <- read_csv(params$ue_data_file, col_types="") %>%
  mutate(rtp_ssrc = as.factor(rtp_ssrc), rtp_pt = as.factor(rtp_pt))

pkts_ue %<>% mutate(ts_s = ts_s - min(pkts_ue$ts_s))
```

```{r}
pkts_ue %>%
  group_by(ip_src, ip_dst, gtp_ip_src, gtp_ip_dst, rtp_ssrc, rtp_pt) %>%
  summarize(n = n(), .groups = "drop")
```
```{r}
pkts_ue %>%
  filter(rtp_pt == 96 | rtp_pt == 111) %>%
  group_by(ts_s, rtp_ssrc, rtp_pt) %>%
  summarize(n = n(), .groups = "drop") %>%
  ggplot(aes(x = ts_s, y = n, color = rtp_ssrc)) +
    labs(x = "Time [s]", y = "# Packets", color = "SSRC") +
    geom_line() +
    theme_om() +
    theme(
      legend.position = c(0.99,0.86)
    )
```

```{r}
pkts_ue %>%
  filter(rtp_pt == 97) %>%
  group_by(ts_s, rtp_ssrc, rtp_pt) %>%
  summarize(n = n(), .groups = "drop") %>%
  ggplot(aes(x = ts_s, y = n, color = rtp_ssrc)) +
    labs(x = "Time [s]", y = "# Packets", color = "SSRC") +
    geom_line() +
    theme_om() +
    theme(
      legend.position = c(0.99,0.89)
    )
```

```{r}
frames <- pkts_ue %>%
  filter(rtp_pt == 96) %>%
  group_by(rtp_ssrc, rtp_ts) %>%
  summarize(ts_s = max(ts_s), ts_us = max(ts_us), n = n(), .groups = "drop")
  
  
frames %>%
  group_by(rtp_ssrc) %>%
  mutate(fps = (rtp_ts - lag(rtp_ts)) / 90) %>%
  # group_by(rtp_ssrc, ts_s) %>%
  # summarize(fps_mean = mean(fps)) %>%
  ggplot(aes(x = ts_s, y = fps, color = rtp_ssrc)) +
    labs(x = "Time [s]", y = "Frame Rate [fps]", color = "SSRC") +
    geom_point() +
    theme_om() +
    theme(
      legend.position = c(0.99,0.89)
    ) +
    facet_wrap(~rtp_ssrc)
```



