---
title: "WebRTC Cellular 03/03 Experiment: One-way Delay"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  pkts_file: "joined.csv"
  dci_file: "dci_log_3565920000.csv"
  fig_path: "fig/"
---

```{R setup, include=FALSE}
source("../r/setup.R")

knitr::opts_chunk$set(dev=c("png", "pdf"), fig.width=9, fig.height=4.5,
  fig.align="center", fig.keep="high",dpi = 300, fig.path=params$fig_path)
```

```{r import}
pkts <- read_csv(params$pkts_file, col_types="nnniiffiinnnnn")
dci <- read_csv(params$dci_file, col_types = "niiiffifiiiiiniiifiiniiiifi")
```

```{r}
dci %>%
  group_by(dci_format) %>% summarize(n = n())
```

```{r, fig.width=3, fig.height=2.8}
dci %>%
  filter(dci_format == "0_1") %>%
  ggplot(aes(x = transport_block_size / 8)) +
    labs(x = "Transport Block Size [B]", y = "CDF") +
    stat_ecdf(color = "dodgerblue4") +
    theme_om()
```

```{r}
max(
  min(pkts %>% mutate(timestamp = ts_s_ue + ts_us_ue / 1e7) %>% select(timestamp)),
  min(dci %>% select(timestamp)))

```

```{r}
bind_rows(
  pkts %>%
    filter(ts_s_ue >= 1711996150 & ts_s_ue < 1711996151) %>%
    mutate(ts = (ts_s_ue + ts_us_ue / 1e6) - 1711996150) %>%
    filter(ts < 0.05) %>%
    select(ts, delay_ms),

  dci %>%
    filter(dci_format == "0_1") %>%
    filter(timestamp >= 1711996150 & timestamp < 1711996151) %>%
    mutate(ts = timestamp - 1711996150) %>%
    filter(ts < 0.05) %>%
    mutate(tbs = transport_block_size / 8) %>%
    select(ts, tbs)
) %>%
  arrange(ts) %>%
  ggplot(aes(x = ts)) +
    geom_segment(aes(x = ts, xend = ts, y = 0, yend = tbs), color = "red") +
    geom_point(aes(y = delay_ms * 200), color = "blue") +
  scale_y_continuous(
    limits = c(0, 10000),
    name = "Transport Block Size [B]",
    sec.axis = sec_axis(trans=~.*0.005, name="One-way Delay [ms]")
  ) +
  theme(
    axis.title.y = element_text(color = "red", size=11),
    axis.title.y.right = element_text(color = "blue", size=11)
  )
```

```{r frame-tbs-detail, fig.width = 12, fig.height = 6}
plot_data <- bind_rows(
  pkts %>%
    filter(ts_s_ue >= 1711996150 & ts_s_ue < 1711996152) %>%
    mutate(ts = (ts_s_ue + ts_us_ue / 1e6) - 1711996150) %>%
    filter(ts < 0.12) %>%
    select(ts, rtp_tw_seq4, delay_ms),
  dci %>%
    filter(dci_format == "0_1") %>%
    filter(timestamp >= 1711996150 & timestamp < 1711996152) %>%
    mutate(ts = timestamp - 1711996150) %>%
    filter(ts < 0.12) %>%
    mutate(tbs = transport_block_size / 8) %>%
    select(ts, tbs)
) %>%
  arrange(ts) 


library(cowplot)

p1 <- ggplot(plot_data, aes(x = ts, xend = ts + delay_ms / 1000, y = rtp_tw_seq4, yend = rtp_tw_seq4)) +
        xlim(0, 0.12) +
        labs(x = "", y = "TWCC Sequence Number") +
        geom_segment(color = "dodgerblue4", linewidth  = 1) +
        theme_om()

p2 <- ggplot(plot_data, aes(x = ts, xend = ts, y = 0, yend = tbs)) +
        xlim(0, 0.12) +
        labs(x = "Time [s]", y = "Trans. Block Size [B]") +
        geom_segment(color = "red3", linewidth  = 0.65) +
        theme_om()

plot_grid(p1, p2, ncol=1, align= "v", rel_heights = c(2, 1))
```




```{r}
bind_rows(
  pkts %>%            
    filter(ts_s_ue >= 1711996150 & ts_s_ue < 1711996151) %>%
    mutate(
      ts_ue = as.numeric(ts_s_ue + (ts_us_ue / 1e7) - 1711996150),
      ts_sink = as.numeric(ts_s_sink + (ts_us_sink / 1e7))) %>%
    select(ts_ue, ts_sink, delay_ms) %>%
    mutate(tbs = as.numeric(NA))
,
  dci %>%
    filter(dci_format == "0_1") %>%
    filter(timestamp >= 1711996150 & timestamp < 1711996151) %>%
    select(timestamp, transport_block_size) %>%
    rename(ts_ue = timestamp, tbs = transport_block_size) %>%
    mutate(
      ts_ue = as.numeric(ts_ue - 1711996150),
      ts_sink = as.numeric(NA), delay_ms = as.numeric(NA))
) %>%
  arrange(ts_ue)

```



```{r}
bind_rows(
  pkts %>%
    filter(ts_s_ue >= 171199650 & ts_s_ue < 1711996151) %>%
    mutate(
      ts_ue = as.numeric(ts_s_ue + (ts_us_ue / 1e7)),
      ts_sink = as.numeric(ts_s_sink + (ts_us_sink / 1e7))) %>%
    select(ts_ue, ts_sink, delay_ms) %>%
    mutate(tbs = as.numeric(NA)
  
           ),
  
  dci %>%
    filter(timestamp >= 1711996150 & timestamp < 1711996151) %>%
    select(timestamp, transport_block_size) %>%
    rename(ts_ue = timestamp, tbs = transport_block_size) %>%
    mutate(ts_sink = as.numeric(NA), delay_ms = as.numeric(NA))
  
  ) %>%
  arrange(ts_ue) %>%
  ggplot(aes(x = ts_ue)) +
    geom_line(aes(y = delay_ms)) +
    geom_point(aes(y = delay_ms))
  
```





```{r}
dci %>%
  filter(timestamp >= 1711996120 & timestamp < 1711996120.05) %>%
  ggplot(aes(x = timestamp, y = transport_block_size / 8)) +
    geom_point()
```





```{r owd-up-cdf, fig.width = 6, fig.height = 4}
pkts %>%
  select(delay_ms) %>%
  ggplot(aes(x = delay_ms)) +
    stat_ecdf(color = "dodgerblue4") +
    xlim(0, NA) +
    labs(title = "RTP Uplink One-Way Delay (UE → WebRTC Sink)", x = "One-Way Delay [ms]", y = "CDF") +
    theme_om()
```

```{r inter-pkt-cdf, fig.width = 6, fig.height = 4}
pkts %>%
  select(ts_ms_rel_ue, ts_ms_rel_sink) %>%
  mutate(ts_ms_rel_delta_ue = ts_ms_rel_ue  - lag(ts_ms_rel_ue)) %>%
  mutate(ts_ms_rel_delta_sink = ts_ms_rel_sink - lag(ts_ms_rel_sink)) %>%
  pivot_longer(c("ts_ms_rel_delta_ue", "ts_ms_rel_delta_sink"), names_to = "type", 
               values_to="ts_ms_rel_delta") %>%
  filter(!is.na(ts_ms_rel_delta)) %>%
  ggplot(aes(x = ts_ms_rel_delta, color = type)) +
    stat_ecdf() +
    labs(title = "RTP Inter-Packet Time (UE → WebRTC Sink)", x = "Time between Packets [ms]", y = "CDF", 
         color = "location") +
    theme_om()
```



```{r}
pkts %>%
  mutate(ts_s_rel_ue = ts_ms_rel_ue / 1000) %>%
  # filter(ts_s_rel_ue < 220) %>%
  ggplot(aes(x = ts_s_rel_ue, y = rtp_tw_seq4)) +
    geom_line()
```


```{r owd-overview, fig.width = 10, fig.height=6}
pkts %>%
  filter(ts_ms_rel_ue > 200000 & ts_ms_rel_ue < 210000) %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  ggplot(aes(x = rtp_tw_seq4_mod1000, y = delay_ms)) +
    labs(x = "RTP TWCC Seq. % 1000", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    scale_x_continuous(breaks = seq(0, 1000, 100), expand = c(0.0125, 0)) +
    geom_line(color = "dodgerblue4") +
    facet_wrap(~slice, ncol=1) +
    theme_om()
```

```{r owd-detail, fig.width = 10, fig.height=4}
pkts %>%
  filter(ts_ms_rel_ue > 219000 & ts_ms_rel_ue < 219500) %>%
  ggplot(aes(x = rtp_tw_seq4, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence No.", y = "UE-Sink one-way delay [ms]") +
    ylim(0, 25) +
    geom_rect(xmin = 63876, xmax=63903, ymin = -1, ymax = 26, color = "red", linetype=2, fill=NA, linewidth = 0.25) +
    geom_line(color = "dodgerblue4") +
    geom_point(color = "dodgerblue4", size = 0.75) +
    theme_om()
```

```{r owd-bars, fig.width = 10, fig.height=2.5}
pkts %>%
  filter(ts_ms_rel_ue > 219000 & ts_ms_rel_ue < 219100) %>%
  ggplot(aes(x = ts_ms_rel_ue, xend = ts_ms_rel_sink, y = rtp_tw_seq4, yend = rtp_tw_seq4)) +
    labs(x = "Time [ms]", y = "RTP TWCC Sequence No.", color = "RTP SSRC") +
    scale_x_continuous(n.breaks = 20, expand = c(0.0125, 0)) +
    geom_segment(linewidth = 1.4, color = "dodgerblue4") +

    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.18, 0.935))
```
