---
title: "WebRTC Cellular 04/08 Experiment (Commercial Cell): One-way Delay"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  pkts_file: "joined.csv"
  fig_path: "fig/"
---

```{R setup, include=FALSE}
source("../r/setup.R")

knitr::opts_chunk$set(dev=c("png", "pdf"), fig.width=9, fig.height=4.5,
  fig.align="center", fig.keep="high",dpi = 300, fig.path=params$fig_path)
```

```{r import}
pkts <- read_csv(params$pkts_file, col_types="nnniiffiinnnnn")
```

```{r owd-up-cdf, fig.width = 5, fig.height = 4}
pkts %>%
  select(delay_ms) %>%
  ggplot(aes(x = delay_ms)) +
    stat_ecdf(color = "dodgerblue4") +
    xlim(0, NA) +
    labs(title = "RTP Uplink One-Way Delay (UE → WebRTC Sink)", x = "One-Way Delay [ms]", y = "CDF") +
    theme_om()
```
```{r inter-pkt-cdf, fig.width = 5, fig.height = 4}
pkts %>%
  select(ts_ms_rel_ue, ts_ms_rel_sink) %>%
  mutate(ts_ms_rel_delta_ue = ts_ms_rel_ue  - lag(ts_ms_rel_ue)) %>%
  mutate(ts_ms_rel_delta_sink = ts_ms_rel_sink - lag(ts_ms_rel_sink)) %>%
  pivot_longer(c("ts_ms_rel_delta_ue", "ts_ms_rel_delta_sink"), names_to = "type", 
               values_to="ts_ms_rel_delta") %>%
  filter(!is.na(ts_ms_rel_delta)) %>%
  ggplot(aes(x = ts_ms_rel_delta, color = type)) +
    xlim(0,50) +
    stat_ecdf() +
    labs(title = "RTP Inter-Packet Time (UE → WebRTC Sink)", x = "Time between Packets [ms]", y = "CDF", 
         color = "location") +
    scale_color_brewer(
      name = "Location",
      palette = "Set1",
      breaks = c("ts_ms_rel_delta_ue", "ts_ms_rel_delta_sink"),
      labels = c("UE","Sink")) +
    theme_om()
```
```{r twcc-seq, fig.width = 6, fig.height = 3}
pkts %>%
  mutate(ts_s_rel_ue = ts_ms_rel_ue / 1000) %>%
  ggplot(aes(x = ts_s_rel_ue, y = rtp_tw_seq4)) +
    geom_line(color = "dodgerblue4") +
    labs(x = "Time [s]", y = "TWCC Sequence Number") +
    theme_om()
```



```{r owd-overview, fig.width = 14, fig.height=8}
pkts %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  filter(ts_ms_rel_ue > 1000 & ts_ms_rel_ue < 27000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  ggplot(aes(x = rtp_tw_seq4_mod1000, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence % 1000", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    scale_x_continuous(breaks = seq(0, 1000, 100), expand = c(0.0125, 0)) +
    geom_line(color = "dodgerblue4") +
    facet_wrap(~slice, ncol=1) +
    theme_om()
```

```{r owd-detail1, fig.width = 10, fig.height=4}
pkts %>%
  filter(ts_ms_rel_ue > 2000 & ts_ms_rel_ue < 3000) %>%
  ggplot(aes(x = rtp_tw_seq4, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence No.", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    geom_rect(xmin = 46233, xmax=46267, ymin = 0, ymax = 100, color = "red", linetype=2, fill=NA, linewidth = 0.25) +
    geom_line(color = "dodgerblue4") +
    geom_point(color = "dodgerblue4", size = 0.75) +
    theme_om()
```
```{r owd-bars1, fig.width = 10, fig.height=2.5}
pkts %>%
  filter(ts_ms_rel_ue > 2000 & ts_ms_rel_ue < 2250) %>%
  ggplot(aes(x = ts_ms_rel_ue, xend = ts_ms_rel_sink, y = rtp_tw_seq4, yend = rtp_tw_seq4)) +
    labs(x = "Time [ms]", y = "RTP TWCC Sequence No.", color = "RTP SSRC") +
    scale_x_continuous(n.breaks = 20, expand = c(0.0125, 0)) +
    geom_segment(linewidth = 1.4, color = "dodgerblue4") +
    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.18, 0.935))
```



```{r owd-detail2, fig.width = 10, fig.height=4}
pkts %>%
  filter(ts_ms_rel_ue > 5000 & ts_ms_rel_ue < 6000) %>%
  ggplot(aes(x = rtp_tw_seq4, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence No.", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    geom_rect(xmin = 46755, xmax=46780, ymin = 0, ymax = 100, color = "red", linetype=2, fill=NA, linewidth = 0.25) +
    geom_line(color = "dodgerblue4") +
    geom_point(color = "dodgerblue4", size = 0.75) +
    theme_om()
```
```{r owd-bars2, fig.width = 10, fig.height=2.5}
pkts %>%
  filter(ts_ms_rel_ue > 5800 & ts_ms_rel_ue < 6000) %>%
  ggplot(aes(x = ts_ms_rel_ue, xend = ts_ms_rel_sink, y = rtp_tw_seq4, yend = rtp_tw_seq4)) +
    labs(x = "Time [ms]", y = "RTP TWCC Sequence No.", color = "RTP SSRC") +
    scale_x_continuous(n.breaks = 20, expand = c(0.0125, 0)) +
    geom_segment(linewidth = 1.4, color = "dodgerblue4") +

    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.18, 0.935))
```