---
- name: synchronize clock
  
  vars:
    ntp_servers:
      - ntp1.cs.princeton.edu
      - ntp2.cs.princeton.edu
  
  hosts:
    - sfu
  
  tasks:
    - name: install chrony
      become: true
      ansible.builtin.apt:
        name: chrony
        state: latest

    - name: configure chrony
      become: true
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf 
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        backup: yes
      notify:
        - reload chrony

    - name: enable chrony
      become: true
      ansible.builtin.service:
        name: chrony
        state: started
        enabled: yes

  handlers:
    - name: reload chrony
      become: true
      ansible.builtin.service:
        name: chrony
        state: restarted