---
title: "Join Test"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  ue_pkts_file: "zoom-0601-ue-pkts.csv"
  core_pkts_file: "zoom-0601-core-pkts.csv"
  join_pkts_up_file: "zoom-0601-join-pkts-up.csv"
---

```{R setup, include=FALSE}
source("../r/setup.R")
```

```{r import}
ue_pkts <- read_csv(params$ue_pkts_file, col_types = "nnfffcicifiniiniff") %>%
  mutate(dir = if_else(tp_dst == 8801, "u", "d")) %>%
  rename("ts_s" = "#ts_s") %>%
  select(-c("flow_type", "ip_proto", "ip_src", "tp_src", "ip_dst", "tp_dst", "drop"))
core_pkts <- read_csv(params$core_pkts_file, col_types = "nnfffcicifiniiniff") %>%
  mutate(dir = if_else(tp_dst == 8801, "u", "d")) %>%
  rename("ts_s" = "#ts_s") %>%
  select(-c("flow_type", "ip_proto", "ip_src", "tp_src", "ip_dst", "tp_dst", "drop"))
```


```{r}
join_up <- full_join(
  ue_pkts %>% filter(dir == "u"),
  core_pkts %>% filter(dir == "u"),
  by = join_by("dir", "media_type", "ssrc", "pt", "rtp_seq", "rtp_ts"),
  suffix = c("_ue", "_core")) %>%
  select(-c("dir")) %>%
  filter(!is.na(ts_s_ue) & !is.na(ts_s_core))
```

```{r}
join_up %<>%
  mutate(
    ts_ms_ue   = (ts_s_ue - min(join_up$ts_s_ue)) * 1000 + ts_us_ue / 1000,
    ts_ms_core = (ts_s_core - min(join_up$ts_s_ue)) * 1000 + ts_us_core / 1000,
    owd_ms     = ts_ms_core - ts_ms_ue) %>%
  write_csv(params$join_pkts_up_file)
```


```{r}
join_up %>%
  group_by(pt, ssrc, media_type) %>%
  summarize(n = n(), dur_min = (max(ts_ms_ue) - min(ts_ms_ue)) / 1000 / 60, .groups = "drop")
```

```{r, fig.width=6, fig.height=3}
join_up %>%
  mutate(ssrc = as.factor(ssrc),
         pt = as.factor(pt),
         ssrc_pt = forcats::fct_cross(ssrc, pt, sep = "/")) %>%
  ggplot(aes(x = ts_ms_ue / 1000 / 60, y = rtp_seq, color = ssrc_pt)) +
    labs(x = "Time [min]", y = "RTP Sequence", color = "SSRC/PT") +
    scale_x_continuous(expand = c(0.02, 0)) +
    scale_y_continuous(expand = c(0.02, 0), limits = c(0, 65536)) +
    geom_line() +
    theme_om() +
    theme(legend.position.inside = c(0.23, 0.78))
```

```{r owd-up-cdf, fig.width=3, fig.height=3}
join_up %>%
  ggplot(aes(x = owd_ms)) +
    labs(x = "One-way Delay [ms]", y = "CDF") +
    scale_x_continuous(expand = c(0.05, 0)) +
    scale_y_continuous(expand = c(0.02, 0)) +
    stat_ecdf(color = color_palette("Set1")[[2]]) +
    theme_om()
```

