---
title: "Zoom 06/01 - One-way Delay / Frames"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
params:
  join_pkts_up_file: "zoom-0601-join-pkts-up.csv"
  ssim_file: "zoom-0601-ssim.csv"
  fig_path: fig/
---

```{R setup, include=FALSE}
source("../r/setup.R")
```

```{r import}
join_pkts_up <- read_csv(params$join_pkts_up_file, col_types = "nnfinfinifnniifnnn")
ssim <- read_csv(params$ssim_file, col_types="iiin", comment="#")
```

```{r owd-up-cdf, fig.width=3, fig.height=3, dpi = 300}
join_pkts_up %>%
  ggplot(aes(x = owd_ms, color = media_type)) +
    labs(x = "One-way Delay [ms]", y = "CDF", color = "Media Type") +
    scale_x_log10(expand = c(0.05, 0), limits = c(1,NA), breaks = c(1, 10, 100)) +
    annotation_logticks(sides = "b", mid = unit(0.15, "cm"), long = unit(0.2, "cm"), color = "gray30") +
    scale_y_continuous(expand = c(0.02, 0)) +
    scale_color_brewer(
        name = "Media Type",
        palette = "Set1",
        breaks = c("a", "v"),
        labels = c("Audio","Video")) +
    stat_ecdf() +
    theme_om() +
    theme(legend.position.inside = c(0.95, 0.2))
```

```{r owd-ts, fig.height = 25}
join_pkts_up %>%
  filter(ssrc == 16789506) %>%
  mutate(
    ts_s = ts_ms_ue / 1000,
    slice = as.integer(ts_s / 15),
    ts_s_mod30 = ts_s %% 15) %>%
  ggplot(aes(x = ts_s_mod30, y = owd_ms)) +
    ylim(0, NA) +
    geom_line(color = "dodgerblue4") +
    geom_point(color = "dodgerblue4", size = 0.6) +
    theme_om() +
    facet_wrap(~slice, ncol = 1)
```

```{r}
rx_video_min_ts <- 1717272270.486
```


```{r}
ssim %<>%
  mutate(it = as.integer(cumsum(if_else(frame_send - lag(frame_send, default = 0) < -100, 1, 0)))) %>%
  mutate(frame_send_seq = as.integer(max(frame_send) * it + frame_send + if_else(it > 0, 1, 0))) %>%
  mutate(ssim = if_else(ssim == -1, NA, ssim)) %>%
  mutate(frame_incr = frame_send_seq - lag(frame_send_seq)) %>%
  mutate(frame_incr = if_else(frame_incr == 0, NA, frame_incr)) %>%
  mutate(rx_ts = 0) %>%
  mutate(rx_ts = lag(rx_ts, default = rx_video_min_ts) + 1/60)
```

```{r fig.width = 5, fig.height = 3}
frames <- join_pkts_up %>%
  group_by(media_type, rtp_ts, ssrc, pt) %>%
  summarize(
    n_pkts = n(),
    ts_min_ue = min(ts_ms_ue),
    ts_max_ue = max(ts_ms_ue),
    spread_ue_egress   = max(ts_ms_ue) - min(ts_ms_ue),
    spread_core_ingress = max(ts_ms_core) - min(ts_ms_core),
    size = sum(pl_len_ue), .groups = "drop")
```

```{r pkts-per-frame-cdf, fig.width = 3, fig.height = 3, dpi = 300}
frames %>%
  ggplot(aes(x = n_pkts, color = media_type)) +
    stat_ecdf() +
    labs(x = "# Packets per Sample/Frame", y = "CDF") +
    scale_color_brewer(
        name = "Media Type",
        palette = "Set1",
        breaks = c("a", "v"),
        labels = c("Audio","Video")) +
    theme_om() +
    theme(legend.position.inside = c(0.95,0.2))
```
* Uniformity of frames


```{r}
frames %>%
  filter(media_type == "v") %>%
  group_by(ssrc, pt) %>%
  summarize(n = n(), .groups = "drop")
```


```{r inter-frame-time-cdf, fig.width = 3, fig.height = 3, dpi = 300}
frames %>%
  filter(media_type == "v") %>%
  filter(pt == 98) %>%
  mutate(inter_frame_delay_ue = ts_min_ue - lag(ts_min_ue)) %>%
  ggplot(aes(x = inter_frame_delay_ue)) +
    labs(x = "Inter-Frame Time [ms]", y = "CDF") +
    scale_x_continuous(limits = c(0, 150)) +
    stat_ecdf(color = "dodgerblue4") +
    theme_om()
```

```{r frame-size-cdf, fig.width = 3, fig.height = 3, dpi = 300}
frames %>%
  filter(media_type == "v") %>%
  filter(pt == 98) %>%
  ggplot(aes(x = size)) +
    labs(x = "Frame Size [B]", y = "CDF") +
    stat_ecdf(color = "dodgerblue4") +
    theme_om()
```

* TODO: check what role RTXs play here

* What happens in cases where the UE-side delay spread for video is substantially larger than zero?


```{r ue-spread-ts, fig.width = 8, fig.height = 2}
frames %>%
  filter(media_type == "v") %>%
  ggplot(aes(x = ts_min_ue, y = spread_ue_egress)) +
    scale_x_continuous(expand = c(0.025, 0)) +
    geom_point(color = "dodgerblue4", size = 0.5) +
    theme_om()
```


```{r}
frames %>%
  filter(media_type == "v" & spread_ue_egress > 5)
```

* Look at the corresponding packets (example 1):

```{r ue-spread-example-1, fig.width = 8, fig.height = 2}
join_pkts_up %>%
  filter(media_type == "v" & rtp_ts == 2547459892) %>%
  ggplot(aes(x = ts_ms_ue, xend = ts_ms_core, y = rtp_seq, yend = rtp_seq)) +
    labs(x = "Time [ms]", y = "RTP Sequence No.") +
    geom_segment(size = 2, color = "dodgerblue4") +
    theme_om()
```

* look at corresponding packets (example 2):

```{r ue-spread-example-2, fig.width = 8, fig.height = 1.7}
join_pkts_up %>%
  filter(media_type == "v" & rtp_ts == 2546994772) %>%
  ggplot(aes(x = ts_ms_ue, xend = ts_ms_core, y = rtp_seq, yend = rtp_seq)) +
    labs(x = "Time [ms]", y = "RTP Sequence No.") +
    geom_segment(size = 2, color = "dodgerblue4") +
    theme_om()
```


```{r latency-spread, fig.width = 6, fig.height = 3, dpi = 300}
frames %>%
  pivot_longer(c("spread_ue_egress", "spread_core_ingress"), names_to = "var", values_to = "val") %>%
  mutate(media_type = case_match(media_type, "a" ~ "Audio", "v" ~ "Video")) %>%
  ggplot(aes(x = val, color = var)) +
    labs(x = "Delay Spread [ms]", y = "CDF", color = "Location") +
    xlim(0,100) +
    scale_color_brewer(
        name = "Location",
        palette = "Set1",
        breaks = c("spread_ue_egress", "spread_core_ingress"),
        labels = c("UE (Egress)","Core (Ingress)")) +
    stat_ecdf() +
    theme_om() +
    facet_wrap(~media_type) +
    theme(legend.position.inside = c(0.98,0.2))
```


```{r, fig.width = 10}
cowplot::plot_grid(
  
  join_pkts_up %>%
    mutate(ts_s = as.numeric(ts_s_ue) + ts_us_ue / 1000000) %>%
    filter(ts_s > rx_video_min_ts) %>%
    mutate(ts_s = ts_s - rx_video_min_ts) %>%
    filter(ts_s > 100 & ts_s < 160) %>%
    ggplot(aes(x = ts_s, y = owd_ms)) +
      scale_x_continuous(expand = c(0.015, 0)) +
      geom_line(color = "dodgerblue4") +
      theme_om(),

  ssim %>%
    group_by(frame_send_seq) %>%
    summarize(frame_receive = min(frame_receive), display_duration_ms = 1/60 * n() * 1000) %>%
    mutate(ts_s = frame_receive / 1/60) %>%
    filter(ts_s > 100 & ts_s < 160) %>%
    ggplot(aes(x = ts_s, y = display_duration_ms)) +
      scale_x_continuous(expand = c(0.015, 0)) +
      geom_line(color = "dodgerblue4") +
      theme_om(),
  
  ssim %>%
    group_by(frame_send_seq) %>%
    summarize(
      frame_receive = min(frame_receive),
      ssim = first(ssim),
      display_duration_ms = 1/60 * n() * 1000) %>%
    mutate(ts_s = frame_receive / 1/60) %>%
    filter(ts_s > 100 & ts_s < 160) %>%
    ggplot(aes(x = ts_s, y = ssim)) +
      scale_x_continuous(expand = c(0.015, 0)) +
      geom_line(color = "dodgerblue4") +
      theme_om(),
  
  ncol = 1, align = "v")
```
