---
title: "Zoom 06/01 - Summary"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
params:
  ssim_file: "zoom-0601-ssim.csv"
  ue_pkts_file: "zoom-0601-ue-pkts.csv"
  core_pkts_file: "zoom-0601-core-pkts.csv"
  join_pkts_up_file: "zoom-0601-join-pkts-up.csv"
  ue_frames_file: "zoom-0601-ue-frames.csv"
  core_frames_file: "zoom-0601-core-frames.csv"
  fig_path: fig/
---

```{R setup, include=FALSE}
source("../r/setup.R")
```

```{r import}
ssim <- read_csv(params$ssim_file, col_types="iiin", comment="#")
ue_pkts <- read_csv(params$ue_pkts_file, col_types = "nnfffcicifiniiniff")
core_pkts <- read_csv(params$core_pkts_file, col_types = "nnfffcicifiniiniff")
join_pkts_up <- read_csv(params$join_pkts_up_file, col_types = "nnfinfinifnniifnnn")
ue_frames <- read_csv(params$ue_frames_file, col_types = "nciciiffnnnnniiiin")
core_frames <- read_csv(params$core_frames_file, col_types = "nciciiffnnnnniiiin")
```

*Generate consecutive sequence over sent frame indices:*

```{r}
ssim %<>%
  mutate(it = as.integer(cumsum(if_else(frame_send - lag(frame_send, default = 0) < -100, 1, 0)))) %>%
  mutate(frame_send_seq = as.integer(max(frame_send) * it + frame_send + if_else(it > 0, 1, 0))) %>%
  mutate(ssim = if_else(ssim == -1, NA, ssim)) %>%
  mutate(frame_incr = frame_send_seq - lag(frame_send_seq)) %>%
  mutate(frame_incr = if_else(frame_incr == 0, NA, frame_incr))
```

*Structural similarity of received frames to sent frames:*

```{r ssim, fig.width = 9, fig.height = 2.5}
ssim %>%
  filter(!is.na(ssim)) %>%
  ggplot(aes(x = frame_send_seq, y = ssim)) +
    labs(x = "Frame Number", y = "SSIM") +
    scale_x_continuous(expand = c(0.02, 0)) +
    geom_line(color = color_palette("Set1")[[2]]) +
    theme_om()
```

*Increment of sent frame indices (based on barcode matching):*

```{r frame-incr, fig.width = 9, fig.height = 2}
ssim %>%
  filter(!is.na(frame_incr)) %>%
  ggplot(aes(x = frame_send_seq, y = frame_incr)) +
    labs(x = "Frame Number", y = "Frame Increment") +
    scale_x_continuous(expand = c(0.02, 0)) +
    geom_point(color = color_palette("Set1")[[2]], size = 0.5) +
    theme_om()
```

*RTP-level jitter:*

```{r jitter, fig.width = 9, fig.height = 2.5}
ue_frames %>%
  filter(tp_src == 8801 & media_type == 16) %>%
  mutate(frame_num = row_number()) %>%
  ggplot(aes(x = frame_num, y = jitter_ms)) +
    labs(x = "Frame Number", y = "Jitter [ms]") +
    geom_line(color = color_palette("Set1")[[2]]) +
    theme_om()
```

*Frame rate:*

```{r fps, fig.width = 9, fig.height = 2.5}
ue_frames %>%
  filter(tp_src == 8801 & media_type == 16) %>%
  mutate(frame_num = row_number()) %>%
  ggplot(aes(x = frame_num, y = fps)) +
    labs(x = "Frame Rate", y = "Frame Number") +
    geom_line(color = color_palette("Set1")[[2]]) +
    theme_om()
```

*Frame size:*

```{r frame-size, fig.width = 9, fig.height = 2.5}
ue_frames %>%
  filter(tp_src == 8801 & media_type == 16) %>%
  mutate(frame_num = row_number(),) %>%
  ggplot(aes(x = frame_num, y = frame_size / 1000)) +
    labs(x = "Frame Number", y = "Frame Size [KB]") +
    geom_line(color = color_palette("Set1")[[2]]) +
    theme_om()
```
