---
title: "5G ICMP Increasing Packet Size 04/29/24: One-Way Delay"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  ue_file: "icmp-bursts-5g-042924-ue.csv"
  srv_file: "icmp-bursts-5g-042924-srv.csv"
  dci_log_file: "icmp-bursts-5g-042924-dci.csv"
---


```{R setup, include=FALSE}
source("../r/setup.R")

knitr::opts_chunk$set(dev=c("png", "pdf"), fig.width=9, fig.height=4.5,
  fig.align="center", fig.keep="high",dpi = 300, fig.path="fig/")
```

```{r import}
ue <- read_csv(params$ue_file, col_types="") %>%
  filter(icmp_type == 8) %>%
  mutate(id = seq_along(ts_s)) %>%
  select(ts_s, ts_us, icmp_seq, pkt_size, id) %>%
  relocate(id)

srv <- read_csv(params$srv_file, col_types="") %>%
  filter(icmp_type == 8) %>%
  mutate(id = seq_along(ts_s)) %>%
  select(ts_s, ts_us, icmp_seq, pkt_size, id) %>%
  relocate(id)

min_ts <- min(min(ue$ts_s), min(srv$ts_s))

ue %<>%
  mutate(ts_s = ts_s - min_ts) %>%
  mutate(ts_ms = ((ts_s * 1000) + (ts_us / 1000))) %>%
  select(-(c(ts_s, ts_us)))

srv %<>%
  mutate(ts_s = ts_s - min_ts) %>%
  mutate(ts_ms = ((ts_s * 1000) + (ts_us / 1000))) %>%
  select(-(c(ts_s, ts_us)))

join <- 
  left_join(ue, srv, by = join_by(id, icmp_seq), suffix = c("_ue", "_srv")) %>%
  select(-pkt_size_srv) %>%
  mutate(delay_ms = ts_ms_srv - ts_ms_ue)

dci <- read_csv(params$dci_log_file, col_types = "nniiffifiiiiiniiifiiniiiifi")

dci %<>%
    filter(dci_format == "0_1") %>%
    mutate(
      ts_s = timestamp - min_ts,
      ts_ms = ts_s * 1000) %>%
    filter(ts_s > 0) %>%
    relocate(ts_s) %>%
    mutate(row = seq_along(ts_s)) %>%
    select(ts_s, ts_ms, k, transport_block_size, redundancy_version, row)
```

```{r tbs-cdf, fig.width=3, fig.height=2.8}
dci %>%
  ggplot(aes(x = transport_block_size)) +
    labs(x = "Transport Block Size [b]", y = "CDF") +
    stat_ecdf(color = "dodgerblue4") +
    theme_om()
```

```{r}
dci %>%
  ggplot(aes(x = ts_s, y = transport_block_size)) +
    labs(x = "Time [s]", y = "Transport Block Size [b]") +
    geom_point(size = 0.25, color = "dodgerblue4") +
    theme_om()
```


```{r owd-cdf, fig.width=3, fig.height=2.8}
join %>%
  ggplot(aes(x = delay_ms)) + 
    labs(x = "One-Way Delay [ms]", y = "CDF") +
    xlim(0, 20) +
    stat_ecdf(color = "dodgerblue4") +
    theme_om()
```

```{r pkt-example, fig.height = 2.5}
join %>%
  filter(id > 350 & id < 358) %>%
  mutate(
    id = id - 350,
    ts_ms_ue = ts_ms_ue - 3136.585,
    ts_ms_srv = ts_ms_srv - 3136.585) %>%
  ggplot(aes(x = ts_ms_ue, xend = ts_ms_srv, y = id, yend = id)) +
    labs(x = "Time [ms]", y = "Packet Index") +
    scale_y_continuous(breaks = seq(1, 7)) +
    scale_x_continuous(breaks = seq(0, 17.5, 2.5)) +
    geom_segment(linewidth = 2, color = "dodgerblue4") +
    theme_om()
```



```{r}

```

```{r}
  dci %>%
    filter(ts_ms >= 3106 & ts_ms < 3212) %>%
    mutate(used = as.factor(case_when(
      row >= 1244 & row <= 1248 ~ TRUE,
      row >= 1256 & row <= 1260 ~ TRUE,
      row >= 1268 & row <= 1272 ~ TRUE,
      row >= 1280 & row <= 1284 ~ TRUE,
      .default = FALSE
    ))) %>%
    mutate(transport_block_size = case_when(
      transport_block_size == 81976 ~ 46104, 
      transport_block_size == 24072 ~ 13576
    ))
```


```{r multiple-pkts-2}

library(cowplot)

plot_grid(
  join %>%
    filter(ts_ms_ue >= 3100 & ts_ms_ue < 3200) %>%
    ggplot(aes(x = ts_ms_ue, xend = ts_ms_srv, y = id, yend = id)) +
      geom_segment(linewidth = 2, color = "dodgerblue4") +
        labs(x = "Time [ms]", y = "Packet Index") +
        theme_om(),
  
  dci %>%
    filter(ts_ms >= 3102 & ts_ms < 3210) %>%
    mutate(used = as.factor(case_when(
      row >= 1244 & row <= 1248 ~ TRUE,
      row >= 1256 & row <= 1260 ~ TRUE,
      row >= 1268 & row <= 1272 ~ TRUE,
      row >= 1280 & row <= 1284 ~ TRUE,
      .default = FALSE
    ))) %>%
    mutate(transport_block_size = case_when(
      transport_block_size == 81976 ~ 46104, 
      transport_block_size == 24072 ~ 13576
    )) %>%
    ggplot(aes(x = ts_ms + k / 2 - 1, xend = ts_ms + k / 2 - 1, y = 0, yend = transport_block_size / 8, color = used)) +
      scale_color_manual(values = c("grey", "darkgreen")) +
      labs(x = "Time [ms]", y = "TBS [B]") +
      geom_segment(linewidth = 4) +
      theme_om() +
      theme(legend.position = "none"),
  
  align = "v",
  ncol = 1,
  rel_heights = c(2.5, 1)
)

```



