---
title: "WebRTC Cellular 04/22 Experiment (Private 4G/RR): RLC Example for NextG Talk"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  dci_file: "rlc/rlc_dci.csv"
  pkt_file: "rlc/rlc_pkt.csv"
  fig_path: "fig/"
---


```{R setup, include=FALSE}
source("../r/setup.R")

knitr::opts_chunk$set(dev=c("png", "pdf"), fig.width=9, fig.height=4.5,
  fig.align="center", fig.keep="high",dpi = 300, fig.path=params$fig_path)
```

```{r import}
pkt <- read_csv(params$pkt_file, col_types="nnni")
dci <- read_csv(params$dci_file, col_types="nii")

min_pkt_ts_ue <- min(pkt$ts_ue)

pkt %<>%
  mutate(
    ts_ue   = ts_ue - min_pkt_ts_ue,
    ts_sink = ts_sink - min_pkt_ts_ue)

dci %<>%
    mutate(type = as.factor(case_when(
      delay <= 30 ~ "harq_rtx",
      delay >  30 ~ "rlc_rtx"))) %>%
    mutate(ts = ts - min_pkt_ts_ue - delay) %>%
    filter(ts > 0)



```

```{r, fig.width = 12, fig.height = 5, warning = FALSE}

library(cowplot)

plot_grid(
  
  pkt %>%
    ggplot(aes(x = ts_ue, y=delay)) +
      geom_line(color = "darkgrey") +
      geom_point(color = "dodgerblue4", size = 1) +
      ylim(0, 150) +
      xlim(0,2000) +
      labs(x = "Time [ms]", y = "One-Way Delay [ms]") +
      theme_om(),
  
  dci %>%
    ggplot() +
      labs(x = "Time [ms]", y = "RTX Delay [ms]") +
      xlim(0,2000) +
      ylim(0,35) +
      geom_segment(data = (dci %>% filter(type == "harq_rtx")), aes(x = ts, xend = ts, y = 0, yend = delay), linewidth = 0.75, color = "darkgreen") +
      geom_segment(data = (dci %>% filter(type == "rlc_rtx")), aes(x = ts, xend = ts, y = 0, yend = 30), color = "darkred") + 
      geom_point(data = (dci %>% filter(type == "rlc_rtx")), aes(x = ts, y = 30), shape = 24, size = 3, color = "darkred", fill = "red") + 
      theme_om(),
  
  align = "v",
  ncol = 1,
  rel_heights = c(2,1))
```

```{r, fig.width = 12, fig.height = 2}

```

