---
title: "Zoom 06/25 5G - Send/Receive Analysis"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
params:
  experiment_name: "zoom-0625-5g"
---

```{R setup, include=FALSE}
source("../../r/setup.R")

config <- list(
  "sender_pkts_file"   = paste(params$experiment_name, "sender-pkts.csv", sep = "-"),
  "receiver_pkts_file" = paste(params$experiment_name, "receiver-pkts.csv", sep = "-")
)
```

```{r import}
# import sender and receiver packets:
sender_pkts <- read_csv(config$sender_pkts_file, col_types = "nnfffcicifiniiniff") %>%
  mutate(dir = if_else(tp_dst == 8801, "u", "d")) %>%
  select(-c("flow_type", "ip_proto", "ip_src", "tp_src", "ip_dst", "tp_dst", "drop"))
receiver_pkts <- read_csv(config$receiver_pkts_file, col_types = "nnfffcicifiniiniff") %>%
  mutate(dir = if_else(tp_src == 8801, "d", "u")) %>%
  select(-c("flow_type", "ip_proto", "ip_src", "tp_src", "ip_dst", "tp_dst", "drop"))
```

```{r time-adjustment}
# convert to relative time stamps:
base_ts_s <- max(min(sender_pkts$ts_s), min(receiver_pkts$ts_s))

sender_pkts %<>%
  filter(ts_s >= base_ts_s) %>%
  mutate(ts_ms = to_ms(ts_s, ts_us, base_ts_s)) %>%
  select(-c(ts_s, ts_us))

receiver_pkts %<>%
  filter(ts_s >= base_ts_s) %>%
  mutate(ts_ms = to_ms(ts_s, ts_us, base_ts_s)) %>%
  select(-c(ts_s, ts_us))
```

```{r}
sender_frames <- sender_pkts %>%
  filter(media_type == "v" & pt != 110) %>%
  group_by(dir, media_type, ssrc, pt, rtp_ts, rtp_ext1) %>%
  summarize(pkts = n(), min_ts_ms = min(ts_ms), max_ts_ms = max(ts_ms), .groups = "drop") %>%
  mutate(frame_rate = map_int(max_ts_ms, \(t) sum(max_ts_ms >= (t - 1000) & max_ts_ms <= t)))

receiver_frames <- sender_pkts %>%
  filter(media_type == "v" & pt != 110) %>%
  group_by(dir, media_type, ssrc, pt, rtp_ts, rtp_ext1) %>%
  summarize(pkts = n(), min_ts_ms = min(ts_ms), max_ts_ms = max(ts_ms), .groups = "drop")
```

```{r}
# packet-level one-way delay:
pkts <- left_join(
  sender_pkts %>%
    select(ssrc, pt, rtp_seq, rtp_ts, rtp_ext1, ts_ms),
  receiver_pkts %>%
    select(ssrc, pt, rtp_seq, rtp_ts, rtp_ext1, ts_ms),
  join_by("ssrc", "pt", "rtp_seq", "rtp_ts", "rtp_ext1"),
  suffix = c("_sender", "_receiver")) %>%
  mutate(owd_ms = ts_ms_receiver - ts_ms_sender) %>%
  filter(!is.na(owd_ms))

```


## Analysis for HotNets Talk

### Latency

```{r, fig.width = 8, fig.height = 3}
pkts %>%
  filter(ts_ms_sender > 750e3 & ts_ms_sender <= 950e3) %>%
  mutate(ts_ms_sender = ts_ms_sender - 750e3) %>%
  mutate(owd_ms_sma = rowMeans(sapply(0:(100 - 1), \(x) lag(owd_ms, x)), na.rm = TRUE)) %>%
  pivot_longer(c("owd_ms", "owd_ms_sma"), names_to="type", values_to="owd_ms") %>%
  ggplot(aes(x = ts_ms_sender / 1e3, y = owd_ms, color = type)) +
    labs(x = "Time at Sender[s]", y = "Packet One-Way Delay [ms]") +
    scale_y_log10(breaks = c(10, 100, 1000), limits = c(10, 4000)) +
    scale_color_manual(values = c("#b8cce1", "dodgerblue4")) +
    annotation_logticks(sides = "l", color = "#333") +
    geom_line() +
    theme_om() +
    theme(legend.position = "none")
```

```{r, fig.width = 8, fig.height = 3}
pkts %>%
  filter(pt == 98) %>%
    filter(ts_ms_sender > 750e3 & ts_ms_sender <= 950e3) %>%
  group_by(ssrc, pt, rtp_ts) %>%
  summarize(n = n(), min_ts_ms_sender = min(ts_ms_sender), max_ts_ms_sender = max(ts_ms_sender),
            min_ts_ms_receiver = min(ts_ms_receiver), max_ts_ms_receiver = max(ts_ms_receiver),
            .groups = "drop") %>%
  mutate(owd_ms = max_ts_ms_receiver - min_ts_ms_sender) %>%
  # filter(min_ts_ms_sender >= 490e3 & min_ts_ms_sender < 1000e3) %>%
  mutate(frame_rate_sender = map_int(max_ts_ms_sender,
         \(t) sum(max_ts_ms_sender >= (t - 1000) & max_ts_ms_sender <= t))) %>%
  mutate(frame_rate_receiver = map_int(max_ts_ms_receiver, 
         \(t) sum(max_ts_ms_receiver >= (t - 1000) & max_ts_ms_receiver <= t))) %>%
  # filter(min_ts_ms_sender >= 500e3) %>%
  select(max_ts_ms_sender, max_ts_ms_receiver, frame_rate_sender, frame_rate_receiver) %>%
  pivot_longer(c("frame_rate_sender", "frame_rate_receiver"), names_to = "side", values_to = "frame_rate") %>%
  ggplot(aes(x = max_ts_ms_sender/ 1000, y = frame_rate, color = side)) +
    labs(x = "Time at Sender [s]", y = "Frame Rate [fps]") +
    scale_color_manual(
      name = "Side",
      values = c("dodgerblue4", "darkred"),
      breaks = c("frame_rate_sender", "frame_rate_receiver"),
      labels = c("Sender","Receiver")) +
    geom_line() +
    theme_om() +
    theme(legend.title = element_blank(), legend.position.inside = c(.97,.85))
```

```{r}

mask <- cross_join(
  pkts %>%
    filter(pt == 98) %>%
      filter(ts_ms_sender > 740e3 & ts_ms_sender <= 950e3) %>%
    group_by(ssrc, pt, rtp_ts, rtp_ext1) %>%
    summarize(.groups = "drop"),
  tibble(rtp_ext1 = as.factor(c("0x500000", "0x577777", "0x5ff777")))
) %>%
  rename(rtp_ext1 = rtp_ext1.y) %>%
  select(-rtp_ext1.x)

expanded <- left_join(
  mask,
  pkts %>%
    filter(pt == 98) %>%
      filter(ts_ms_sender > 740e3 & ts_ms_sender <= 950e3,) %>%
    group_by(ssrc, pt, rtp_ts, rtp_ext1) %>%
    summarize(n = n(), min_ts_ms_sender = min(ts_ms_sender), .groups = "drop"),
  by = join_by(ssrc, pt, rtp_ts, rtp_ext1)
) %>%
  group_by(ssrc, pt, rtp_ts, rtp_ext1) %>%
  summarize(n = n, min_ts_ms_sender = min_ts_ms_sender, .groups = "drop") %>%
  fill(min_ts_ms_sender, .direction = "downup") %>%
  mutate(n = if_else(is.na(n), 0, n), seen = as.integer(if_else(n > 0, 1, 0)))

bind_rows(
  expanded %>%
    ungroup() %>%
    filter(rtp_ext1 == "0x500000") %>%
    mutate(frame_rate = map_int(min_ts_ms_sender, 
      ~ sum(seen[min_ts_ms_sender >= (.x - 1000) & min_ts_ms_sender <= .x]))) %>%
    select(-seen),
  
  expanded %>%
    ungroup() %>%
    filter(rtp_ext1 == "0x577777") %>%
    mutate(frame_rate = map_int(min_ts_ms_sender, 
      ~ sum(seen[min_ts_ms_sender >= (.x - 1000) & min_ts_ms_sender <= .x]))) %>%
    select(-seen),
  
  expanded %>%
    ungroup() %>%
    filter(rtp_ext1 == "0x5ff777") %>%
    mutate(frame_rate = map_int(min_ts_ms_sender, 
      ~ sum(seen[min_ts_ms_sender >= (.x - 1000) & min_ts_ms_sender <= .x]))) %>%
    select(-seen)
) %>%
  select(min_ts_ms_sender, rtp_ext1, frame_rate) %>%
  arrange(min_ts_ms_sender) %>%
  filter(min_ts_ms_sender > 750e3) %>%
  ggplot(aes(x = min_ts_ms_sender / 1000, y = frame_rate, color = rtp_ext1, fill = rtp_ext1)) +
    scale_color_brewer(
      name = "SVC Layer",
      palette = "Set1",
      breaks = c("0x500000", "0x577777", "0x5ff777"),
      labels = c("Base","Low-FPS Enhanc.", "High-FPS Enhanc.")) +
    scale_fill_brewer(
      name = "SVC Layer",
      palette = "Pastel1",
      breaks = c("0x500000", "0x577777", "0x5ff777"),
      labels = c("Base","Low-FPS Enhanc.", "High-FPS Enhanc.")) +
    # geom_line()
    # geom_line(position = "stack")
    geom_area(position="stack", linewidth = 0.3)
  
```









```{r, fig.width = 4, fig.height = 3}
pkts %>%
  filter(ts_ms_sender > 900e3 & ts_ms_sender <= 1000e3) %>%
  mutate(owd_ms_sma = rowMeans(sapply(0:(100 - 1), \(x) lag(owd_ms, x)), na.rm = TRUE)) %>%
  pivot_longer(c("owd_ms", "owd_ms_sma"), names_to="type", values_to="owd_ms") %>%
  ggplot(aes(x = ts_ms_sender / 1e3, y = owd_ms, color = type)) +
    labs(x = "Time at Sender[s]", y = "Packet One-Way Delay [ms]") +
    scale_y_log10(breaks = c(10, 100, 1000), limits = c(10, 4000)) +
    scale_color_manual(values = c("#b8cce1", "dodgerblue4")) +
    annotation_logticks(sides = "l", color = "#333") +
    geom_line() +
    theme_om() +
    theme(legend.position = "none")
```

```{r, fig.width = 4, fig.height = 3}
pkts %>%
  filter(ts_ms_sender > 800e3 & ts_ms_sender <= 900e3) %>%
  mutate(owd_ms_sma = rowMeans(sapply(0:(100 - 1), \(x) lag(owd_ms, x)), na.rm = TRUE)) %>%
  pivot_longer(c("owd_ms", "owd_ms_sma"), names_to="type", values_to="owd_ms") %>%
  ggplot(aes(x = ts_ms_sender / 1e3, y = owd_ms, color = type)) +
    labs(x = "Time at Sender[s]", y = "Packet One-Way Delay [ms]") +
    scale_y_log10(breaks = c(10, 100, 1000), limits = c(10, 4000)) +
    scale_color_manual(values = c("#b8cce1", "dodgerblue4")) +
    annotation_logticks(sides = "l", color = "#333") +
    geom_line() +
    theme_om() +
    theme(legend.position = "none")
```

```{r, fig.width = 4, fig.height = 3}
pkts %>%
  filter(pt == 98) %>%
  group_by(ssrc, pt, rtp_ts) %>%
  summarize(n = n(), min_ts_ms_sender = min(ts_ms_sender), max_ts_ms_sender = max(ts_ms_sender),
            min_ts_ms_receiver = min(ts_ms_receiver), max_ts_ms_receiver = max(ts_ms_receiver),
            .groups = "drop") %>%
  mutate(owd_ms = max_ts_ms_receiver - min_ts_ms_sender) %>%
  filter(min_ts_ms_sender >= 490e3 & min_ts_ms_sender < 1000e3) %>%
  mutate(frame_rate_sender = map_int(max_ts_ms_sender,
         \(t) sum(max_ts_ms_sender >= (t - 1000) & max_ts_ms_sender <= t))) %>%
  mutate(frame_rate_receiver = map_int(max_ts_ms_receiver, 
         \(t) sum(max_ts_ms_receiver >= (t - 1000) & max_ts_ms_receiver <= t))) %>%
  filter(min_ts_ms_sender >= 500e3) %>%
  select(max_ts_ms_sender, frame_rate_sender, frame_rate_receiver) %>%
  pivot_longer(c("frame_rate_sender", "frame_rate_receiver"), names_to = "side", values_to = "frame_rate") %>%
  ggplot(aes(x = max_ts_ms_sender/ 1000, y = frame_rate, color = side)) +
    labs(x = "Time at Sender [s]", y = "Frame Rate [fps]") +
    scale_color_manual(
      name = "Side",
      values = c("dodgerblue4", "darkred"),
      breaks = c("frame_rate_sender", "frame_rate_receiver"),
      labels = c("Sender","Receiver")) +
    geom_line() +
    theme_om() +
    theme(legend.title = element_blank(), legend.position.inside = c(.97,.85))
```











## Detailed 30-second Analysis

```{r}
frames_detail <- pkts %>%
  filter(ts_ms_sender >= 260e3 & ts_ms_sender < 290e3) %>%
  group_by(ssrc, pt, rtp_ts) %>%
  summarize(n = n(), min_ts_ms_sender = min(ts_ms_sender), max_ts_ms_sender = max(ts_ms_sender),
            min_ts_ms_receiver = min(ts_ms_receiver), max_ts_ms_receiver = max(ts_ms_receiver),
            .groups = "drop") %>%
  mutate(owd_ms = max_ts_ms_receiver - min_ts_ms_sender)
```

```{r fig.width = 8, fig.height = 3}
frames_detail %>%
  filter(pt == 98) %>%
  ggplot(aes(x = min_ts_ms_sender / 1e3, y = owd_ms)) +
    labs(x = "Send Time [s]", y = "Packet One-Way Delay [ms]") +
    geom_line(color = "dodgerblue4") +
    geom_point(size = 0.5, color = "dodgerblue4") +
    theme_om()
```

```{r fig.width = 8, fig.height = 2}
frames_detail %>%
  filter(pt == 98) %>%
  ggplot(aes(x = min_ts_ms_sender / 1000, xend = max_ts_ms_receiver / 1000, 
             y = rtp_ts / 1e6, yend = rtp_ts / 1e6)) +
    labs(x = "Time [s]", y = "RTP Timestamp / 1e6") +
    geom_segment(linewidth = 1, color = "dodgerblue4") +
    theme_om()
```

```{r fig.width = 8, fig.height = 2}
frames_detail %>%
  filter(pt == 98) %>%
  filter(min_ts_ms_sender >= 280e3 & min_ts_ms_sender < 288e3) %>%
  ggplot(aes(x = min_ts_ms_sender / 1000, xend = max_ts_ms_receiver / 1000, 
             y = rtp_ts / 1e6, yend = rtp_ts / 1e6)) +
    labs(x = "Time [s]", y = "RTP Timestamp / 1e6") +
    geom_segment(linewidth = 1, color = "dodgerblue4") +
    theme_om()
```



```{r fig.width = 8, fig.height = 3}
frames_detail %>%
  filter(pt == 98) %>%
  mutate(frame_rate_sender = map_int(max_ts_ms_sender,
         \(t) sum(max_ts_ms_sender >= (t - 1000) & max_ts_ms_sender <= t))) %>%
  mutate(frame_rate_receiver = map_int(max_ts_ms_receiver, 
         \(t) sum(max_ts_ms_receiver >= (t - 1000) & max_ts_ms_receiver <= t))) %>%
  select(max_ts_ms_sender, frame_rate_sender, frame_rate_receiver) %>%
  pivot_longer(c("frame_rate_sender", "frame_rate_receiver"), names_to = "side",
               values_to = "frame_rate") %>%
  ggplot(aes(x = max_ts_ms_sender / 1000, y = frame_rate, color = side)) +
    labs(x = "Frame Send Time [s]", y = "Frame Rate [fps]") +
    scale_color_manual(
      name = "Side",
      values = c("dodgerblue4", "darkred"),
      breaks = c("frame_rate_sender", "frame_rate_receiver"),
      labels = c("Sender","Receiver")) +
    geom_line() +
    geom_point(size = 0.5) +
    theme_om() + 
    theme(legend.position = c(0.98, 0.8))
```


```{r fig.width = 8, fig.height = 3}
frames_detail %>%
  filter(pt == 98) %>%
  mutate(frame_rate_sender = map_int(max_ts_ms_sender,
         \(t) sum(max_ts_ms_sender >= (t - 1000) & max_ts_ms_sender <= t))) %>%
  mutate(frame_rate_receiver = map_int(max_ts_ms_receiver, 
         \(t) sum(max_ts_ms_receiver >= (t - 1000) & max_ts_ms_receiver <= t))) %>%
  select(min_ts_ms_sender, max_ts_ms_receiver, frame_rate_sender, frame_rate_receiver) %>%
  pivot_longer(c("frame_rate_sender", "frame_rate_receiver"), names_to = "side",
               values_to = "frame_rate") %>%
  ggplot(aes(x = max_ts_ms_receiver / 1000, y = frame_rate, color = side)) +
    labs(x = "Frame Receive Time [s]", y = "Frame Rate [fps]") +
    scale_color_manual(
      name = "Side",
      values = c("dodgerblue4", "darkred"),
      breaks = c("frame_rate_sender", "frame_rate_receiver"),
      labels = c("Sender","Receiver")) +
    geom_line() +
    geom_point(size = 0.5) +
    theme_om() + 
    theme(legend.position = c(0.98, 0.8))
```

```{r fig.width = 8, fig.height = 1.8}
frames_detail %>%
  filter(pt == 98) %>%
  select(rtp_ts, max_ts_ms_sender) %>%
  mutate(max_ts_s_sender = as.integer(max_ts_ms_sender / 1e3)) %>%
  group_by(max_ts_s_sender) %>%
  summarize(frame_rate = n()) %>%
  ggplot(aes(x = max_ts_s_sender, y = frame_rate)) +
    labs(x = "Frame Send Time [s]", y = "Frame Rate [fps]") +
    ylim(0, NA) +
    geom_line(color = "dodgerblue4") +
    geom_point(color = "dodgerblue4") +
    theme_om()
```

```{r fig.width = 8, fig.height = 1.8}
frames_detail %>%
  filter(pt == 98) %>%
  select(rtp_ts, max_ts_ms_receiver) %>%
  mutate(max_ts_s_receiver = as.integer(max_ts_ms_receiver / 1e3)) %>%
  group_by(max_ts_s_receiver) %>%
  summarize(frame_rate = n()) %>%
  ggplot(aes(x = max_ts_s_receiver, y = frame_rate)) +
    labs(x = "Frame Receive Time [s]", y = "Frame Rate [fps]") +
    ylim(0, NA) +
    geom_line(color = "darkred") +
    geom_point(color = "darkred") +
    theme_om()
```


```{r fig.width = 8, fig.height = 1.8}
pkts %>%
  # filter(ts_ms_sender >= 280e3 & ts_ms_sender < 320e3) %>%
  group_by(ssrc, pt, rtp_ts) %>%
  summarize(n = n(), min_ts_ms_sender = min(ts_ms_sender), max_ts_ms_sender = max(ts_ms_sender),
            min_ts_ms_receiver = min(ts_ms_receiver), max_ts_ms_receiver = max(ts_ms_receiver),
            .groups = "drop") %>%
  mutate(owd_ms = max_ts_ms_receiver - min_ts_ms_sender) %>%
  
  filter(pt == 98) %>%
  select(rtp_ts, max_ts_ms_receiver) %>%
  mutate(max_ts_s_receiver = as.integer(max_ts_ms_receiver / 1e3)) %>%
  group_by(max_ts_s_receiver) %>%
  summarize(frame_rate = n()) %>%
  ggplot(aes(x = max_ts_s_receiver, y = frame_rate)) +
    labs(x = "Frame Receive Time [s]", y = "Frame Rate [fps]") +
    ylim(0, NA) +
    geom_line(color = "darkred") +
    theme_om()
```

```{r fig.width = 8, fig.height = 1.8}
pkts %>%
  filter(ts_ms_receiver >= 250e3 & ts_ms_receiver < 350e3) %>%
  group_by(ssrc, pt, rtp_ts) %>%
  summarize(n = n(), min_ts_ms_sender = min(ts_ms_sender), max_ts_ms_sender = max(ts_ms_sender),
            min_ts_ms_receiver = min(ts_ms_receiver), max_ts_ms_receiver = max(ts_ms_receiver),
            .groups = "drop") %>%
  mutate(owd_ms = max_ts_ms_receiver - min_ts_ms_sender) %>%
  filter(pt == 98) %>%
  select(rtp_ts, max_ts_ms_receiver) %>%
  mutate(max_ts_s_receiver = as.integer(max_ts_ms_receiver / 1e3)) %>%
  group_by(max_ts_s_receiver) %>%
  summarize(frame_rate = n()) %>%
  ggplot(aes(x = max_ts_s_receiver, y = frame_rate)) +
    labs(x = "Frame Receive Time [s]", y = "Frame Rate [fps]") +
    ylim(0, NA) +
    geom_line(color = "darkred") +
    geom_point(color = "darkred", size = 0.75) +
    theme_om()
```