---
title: "WebRTC Cellular 04/19 Experiment (Private 4G/RR): One-Way Delay"
output:
  html_document:
    df_print: paged
params:
  pkts_file: "p2p-4g-rr-041924-rtp-join.csv"
  fig_path: "fig/"
---

```{R setup, include=FALSE}
source("../r/setup.R")

knitr::opts_chunk$set(dev=c("png", "pdf"), fig.width=9, fig.height=4.5,
  fig.align="center", fig.keep="high",dpi = 300, fig.path=params$fig_path)
```

```{r import}
pkts <- read_csv(params$pkts_file, col_types="nnniiffiinnnnn")
```

```{r owd-up-cdf, fig.width = 5, fig.height = 4}
pkts %>%
  select(delay_ms) %>%
  ggplot(aes(x = delay_ms)) +
    stat_ecdf(color = "dodgerblue4") +
    xlim(0, 100) +
    labs(title = "RTP Uplink One-Way Delay (UE → WebRTC Sink)", x = "One-Way Delay [ms]", y = "CDF") +
    theme_om()
```


```{r inter-pkt-cdf, fig.width = 5, fig.height = 4}
pkts %>%
  select(ts_ms_rel_ue, ts_ms_rel_sink) %>%
  mutate(ts_ms_rel_delta_ue = ts_ms_rel_ue  - lag(ts_ms_rel_ue)) %>%
  mutate(ts_ms_rel_delta_sink = ts_ms_rel_sink - lag(ts_ms_rel_sink)) %>%
  pivot_longer(c("ts_ms_rel_delta_ue", "ts_ms_rel_delta_sink"), names_to = "type", 
               values_to="ts_ms_rel_delta") %>%
  filter(!is.na(ts_ms_rel_delta)) %>%
  ggplot(aes(x = ts_ms_rel_delta, color = type)) +
    xlim(0,50) +
    stat_ecdf() +
    labs(title = "RTP Inter-Packet Time (UE → WebRTC Sink)", x = "Time between Packets [ms]", y = "CDF", 
         color = "location") +
    scale_color_brewer(
      name = "Location",
      palette = "Set1",
      breaks = c("ts_ms_rel_delta_ue", "ts_ms_rel_delta_sink"),
      labels = c("UE","Sink")) +
    theme_om()
```
```{r twcc-seq, fig.width = 6, fig.height = 2.5}
pkts %>%
  mutate(ts_s_rel_ue = ts_ms_rel_ue / 1000) %>%
  ggplot(aes(x = ts_s_rel_ue, y = rtp_tw_seq4)) +
    geom_line(color = "dodgerblue4") +
    labs(x = "Time [s]", y = "TWCC Sequence Number") +
    theme_om()

```
```{r}
pkts %>%
  mutate(ts_s_rel_ue = ts_ms_rel_ue / 1000) %>%
  filter(rtp_tw_seq4 < 4) %>%
  select(rtp_tw_seq4,ts_s_rel_ue)
```


```{r rtp-seq, fig.width = 6, fig.height = 2.5}
pkts %>%
  filter(rtp_ts > 0) %>%
  mutate(ts_s_rel_ue = ts_ms_rel_ue / 1000) %>%
  ggplot(aes(x = ts_s_rel_ue, y = rtp_seq, color = rtp_pt)) +
    geom_line() +
    scale_color_brewer(palette="Set1") +
    labs(x = "Time [s]", y = "RTP Sequence Number") +
    theme_om()
```


```{r rtp-ts, fig.width = 6, fig.height = 2.5}
pkts %>%
  filter(rtp_ts > 0) %>%
  mutate(ts_s_rel_ue = ts_ms_rel_ue / 1000) %>%
  ggplot(aes(x = ts_s_rel_ue, y = rtp_ts)) +
    geom_line(color = "dodgerblue4") +
    labs(x = "Time [s]", y = "RTP Timestamp") +
    theme_om()
```

```{r}
pkts %>%
  mutate(ts_s_rel_ue = ts_ms_rel_ue / 1000) %>%
  filter(rtp_tw_seq4 < 4) %>%
  select(rtp_tw_seq4,ts_s_rel_ue)
```

```{r owd-overview-1, fig.width = 14, fig.height=80}
pkts %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  filter(ts_ms_rel_ue > 0 & ts_ms_rel_ue < 226000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  ggplot(aes(x = rtp_tw_seq4_mod1000, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence % 1000", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    scale_x_continuous(breaks = seq(0, 1000, 100), expand = c(0.0125, 0)) +
    geom_line(color = "dodgerblue4") +
    facet_wrap(~slice, ncol=1) +
    theme_om()
```

```{r owd-overview-2, fig.width = 14, fig.height=80}
pkts %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  filter(ts_ms_rel_ue > 226000 & ts_ms_rel_ue < 439000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  ggplot(aes(x = rtp_tw_seq4_mod1000, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence % 1000", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    scale_x_continuous(breaks = seq(0, 1000, 100), expand = c(0.0125, 0)) +
    geom_line(color = "dodgerblue4") +
    facet_wrap(~slice, ncol=1) +
    theme_om()
```

```{r owd-overview-3, fig.width = 14, fig.height=80}
pkts %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  filter(ts_ms_rel_ue > 439000 & ts_ms_rel_ue < 754000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  ggplot(aes(x = rtp_tw_seq4_mod1000, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence % 1000", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    scale_x_continuous(breaks = seq(0, 1000, 100), expand = c(0.0125, 0)) +
    geom_line(color = "dodgerblue4") +
    facet_wrap(~slice, ncol=1) +
    theme_om()
```

```{r owd-overview-4, fig.width = 14, fig.height=80}
pkts %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  filter(ts_ms_rel_ue > 754000 & ts_ms_rel_ue < 944000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  ggplot(aes(x = rtp_tw_seq4_mod1000, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence % 1000", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    scale_x_continuous(breaks = seq(0, 1000, 100), expand = c(0.0125, 0)) +
    geom_line(color = "dodgerblue4") +
    facet_wrap(~slice, ncol=1) +
    theme_om()
```


```{r owd-overview-5, fig.width = 14, fig.height=80}
pkts %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  filter(ts_ms_rel_ue > 944000 & ts_ms_rel_ue < 1101000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  ggplot(aes(x = rtp_tw_seq4_mod1000, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence % 1000", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    scale_x_continuous(breaks = seq(0, 1000, 100), expand = c(0.0125, 0)) +
    geom_line(color = "dodgerblue4") +
    facet_wrap(~slice, ncol=1) +
    theme_om()
```

```{r, fig.width = 14, fig.height=20}
pkts %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  filter(ts_ms_rel_ue > 0 & ts_ms_rel_ue < 226000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  mutate(rtp_tw_seq4_mod100 = rtp_tw_seq4_mod1000 %% 100) %>%
  mutate(subslice = as.integer(rtp_tw_seq4_mod1000 / 100)) %>%
  filter(slice == 25) %>%
  ggplot(aes(x = rtp_tw_seq4_mod100, y = delay_ms)) +
    labs(x = "RTP TWCC Sequence % 1000", y = "UE-Sink one-way delay [ms]") +
    ylim(0, NA) +
    geom_line(color = "dodgerblue4") +
    geom_point(color = "dodgerblue4") +
    theme_om() +
    facet_wrap(~subslice, ncol=1)

```

```{r}
pkts %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  filter(ts_ms_rel_ue > 944000 & ts_ms_rel_ue < 1101000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  filter(slice == 9 & rtp_tw_seq4_mod1000 > 500 & rtp_tw_seq4_mod1000 < 600) %>%
  mutate(rtp_ts = as.factor(rtp_ts)) %>%
  ggplot(aes(x = rtp_tw_seq4_mod1000, y = delay_ms, color = rtp_ts)) +
    labs(x = "RTP TWCC Sequence % 1000", y = "UE-Sink one-way delay [ms]") +
    ylim(0,NA) +
    # scale_x_continuous(breaks = seq(0, 1000, 100), expand = c(0.0125, 0)) +
    # geom_line() +
    geom_point() +
    theme_om()
```

```{r}
pkts %>%
  mutate(rtp_tw_seq4_mod1000 = rtp_tw_seq4 %% 1000) %>%
  filter(ts_ms_rel_ue > 944000 & ts_ms_rel_ue < 1101000) %>%
  mutate(slice = as.integer(rtp_tw_seq4 / 1000)) %>%
  filter(slice == 7 & rtp_tw_seq4_mod1000 > 500 & rtp_tw_seq4_mod1000 < 542) %>%
  ggplot(aes(x = ts_ms_rel_ue, xend = ts_ms_rel_sink, y = rtp_tw_seq4_mod1000, yend = rtp_tw_seq4_mod1000)) +
    labs(x = "Time [ms]", y = "RTP TWCC Sequence No.", color = "RTP SSRC") +
    scale_x_continuous(n.breaks = 20, expand = c(0.0125, 0)) +
    geom_segment(linewidth = 1.4, color = "dodgerblue4") +
    theme_om() +
    theme(legend.direction = "horizontal", legend.position = c(0.18, 0.935))
```

